---
ID: "12cddff3-1a9c-4046-b350-e5c0fa2aca45"
Parent: "8ee3468e-dcde-49b7-8a2d-ed1e668b3d70"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/Layouts/Project/Commons/default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: /Views/Commons/default.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201223T131348Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4eb6eb2-7288-48c8-bea1-2928757ebb4b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20201223T131348Z
